### ISSUE TITLE
Compilation error when using clang

### ISSUE THREAD

**Issue by lukaszdaniel** [rho-devel/rho#118] opened 2016-08-18 18:41 UTC
During compilation when using clang, I get the following error:
```
Symbol.o: In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:961: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
Symbol.o: In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:965: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My setup is as follows:
```
./configure --enable-llvm-jit=yes --enable-byte-compiled-packages=yes --with-llvm=/usr/bin/llvm-config-3.8
make
```
Compiler, libboost and system:
clang version 3.8.0
libboost-dev version 1.58.0
Ubuntu 16.04

**Comment by kmillar** [comment] 2016-08-23 04:45
Hi Lukasz,

I'm not able to reproduce this.  Can you double-check that it occurs when building from a clean directory?  If it does, can you include the link command that the build uses?

Thanks

**Comment by lukaszdaniel** [comment] 2016-08-24 18:46
I did the following:
```
export CXX=clang++
export CC=clang
git clean -fdx
tools/rsync-recommended
./configure --enable-llvm-jit=yes --enable-byte-compiled-packages=no --with-llvm=/usr/bin/llvm-config-3.8
make
```
Result was:
```
Symbol.o: In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:961: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
Symbol.o: In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:965: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kmillar** [comment] 2016-08-24 19:05
It looks like this is a nasty gcc-5.1+ / clang compatibility issue unrelated to rho.

For more context, see:
   * https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html
   * https://llvm.org/bugs/show_bug.cgi?id=23529

Closing as there doesn't seem to be much that rho can/should do about this.

**Closed by kmillar** 2016-08-24 19:05 UTC
